Adding components and refactoring of schedulers
Project-MONAI/GenerativeModels pull request #285
Opened 2023-03-06 14:00 UTC by ericspod

Addresses #280.

The objective here is define a base class for all schedulers that we can use for reducing duplication of code and type checking. 

One thing added is a way of adding new noise schedule functions by adding them to a component store object. This version adds the cosine schedule but others can be added by users in their own scripts.

2023-03-23 18:51 UTC, marksgraham commented
Hi @ericspod 
Sorry for taking so long, now GTC+MICCAI are out the way I'll be more responsive. 

> We could do that easily enough, my concern in MONAI and elsewhere is to make explicit what functions are available and give them useful names. We have enumerations for int and string constants in MONAI for this reason as opposed to the way other libraries take of just stating valid values in the docstring. Our layer factories make it easy to choose a layer by name with the dimensionality being parameter, but they also gives clear names to the concepts they store. [Explicit is better than implicit, but simple is better than complex](https://peps.python.org/pep-0020/) so the question is if the tradeoff makes sense here.

OK, then I think the tradeoff does make sense here! I guess the next step is to update all the other schedulers? In which case I'll hold off carefully reviewing the latest batch of changes until thats done?

2023-03-30 17:36 UTC, ericspod commented
Hi @marksgraham, I have things updated finally if you want to take a look.

2023-04-03 19:32 UTC, marksgraham commented
Hi @ericspod 
I've taken a look and looks good - shall I hold off until you've fixed the schedule to do a formal review?
NB that the diffusion tutorials will have to be updated. Because you've kept the defaults the same it should be sufficient to just update the arguments, I don't think youll need to rerun all the notebooks.

2023-04-04 16:24 UTC, Warvito requested changes

2023-04-04 16:24 UTC, Warvito commented on generative/networks/schedulers/scheduler.py
> +    def __init__(self, num_train_timesteps: int = 1000, schedule: str = "linear", **schedule_args) -> None:
typo `linear_beta`

2023-04-05 16:52 UTC, ericspod commented on generative/networks/schedulers/scheduler.py
> +def _cosine_beta(num_train_timesteps, s=8e-3):
`s` is referenced in the paper so I'd leave it here to be consistent with that.

2023-04-05 17:51 UTC, ericspod commented
@Warvito Updates from comments added!

2023-05-15 17:35 UTC, marksgraham approved these changes
Hi @ericspod 

This looks good. Just need to run `./runtests.sh --autofix` as it picks up some formatting corrections

2023-05-15 17:35 UTC, marksgraham commented on generative/networks/schedulers/ddpm.py
> +            raise ValueError("Argument `prediction_type` must be a member of `DDPMPRedictionType`")
```suggestion
            raise ValueError("Argument `prediction_type` must be a member of `DDPMPredictionType`")
```

2023-05-16 14:17 UTC, Warvito commented
I am getting these flake8 errors when running `./runtests.sh -f -u --net`

```
flake8
6.0.0 (flake8-bugbear: 22.12.6, flake8-comprehensions: 3.10.1, flake8-executable: 2.1.2, mccabe: 0.7.0, pep8-naming: 0.13.3, pycodestyle: 2.10.0, pyflakes: 3.0.1) CPython 3.10.6 on Linux
/media/walter/Storage/Projects/GenerativeModels/generative/networks/schedulers/ddim.py:89:30: F541 f-string is missing placeholders
/media/walter/Storage/Projects/GenerativeModels/generative/networks/schedulers/pndm.py:92:30: F541 f-string is missing placeholders
/media/walter/Storage/Projects/GenerativeModels/generative/networks/schedulers/scheduler.py:35:1: F401 'typing.Callable' imported but unused
/media/walter/Storage/Projects/GenerativeModels/generative/networks/schedulers/scheduler.py:37:1: F401 'numpy as np' imported but unused
/media/walter/Storage/Projects/GenerativeModels/generative/utils/__init__.py:16:1: F403 'from .misc import *' used; unable to detect undefined names
2     F401 'typing.Callable' imported but unused
1     F403 'from .misc import *' used; unable to detect undefined names
2     F541 f-string is missing placeholders
```

2023-05-16 15:50 UTC, ericspod commented
@Warvito I've made those fixes but my version of the tools brought up some other issues, different versions of flake8 keep coming up with new issues not seem before.

2023-05-16 16:05 UTC, marksgraham commented
Do we need to settle on a version of flake8 to use then?

2023-05-16 16:28 UTC, ericspod commented
We should always use the current version I think, it just means we'll encounter errors unrelated to our own changes on occasion.

2023-05-16 20:14 UTC, Warvito approved these changes

2023-05-16 20:15 UTC, merged