373 add code for spade vae gan
Project-MONAI/GenerativeModels pull request #405
Opened 2023-06-22 08:04 UTC by virginiafdez

- Added support for SPADE-GAN network (SPADE normalisation and GAN-VAEGAN-like generator)
- Added unit tests
- Added tutorial for 2D usage of SPADE-GAN along with Multi-Scale Discriminator.

2023-06-27 20:37 UTC, marksgraham requested changes
Hi,

Looks good! Some changes requested in the comments

2023-06-27 20:37 UTC, marksgraham commented on generative/networks/nets/spade_network.py
> +class SPADE_ResNetBlock(nn.Module):
please add a docstring

2023-06-27 20:37 UTC, marksgraham commented on generative/networks/nets/spade_network.py
> +class SPADE_Encoder(nn.Module):
docstrng here too

2023-06-27 20:37 UTC, marksgraham commented on generative/networks/nets/spade_network.py
> +
remove blank lines between the def and the function content

2023-06-27 20:37 UTC, marksgraham commented on generative/networks/nets/spade_network.py
> +
remove blank lines

2023-07-05 07:37 UTC, virginiafdez commented on tutorials/generative/2d_autoencoderkl/2d_autoencoderkl_tutorial.ipynb
> +    "from pathlib import Path\n",
I see this line in the tutorial, a bit above

2023-07-05 07:57 UTC, virginiafdez commented on generative/networks/blocks/spade_norm.py
> +        out = normalized * (1 + gamma) + beta
It's in their original code

2023-07-05 07:59 UTC, virginiafdez commented on generative/networks/blocks/spade_norm.py
> +        out = normalized * (1 + gamma) + beta
It comes out (I think) of taking h out of equation (1) (replacing mu by the content of equation 2)

2023-07-05 08:42 UTC, virginiafdez commented
Added requested changes:

- Added more info to the tutorial and loss plot
- Removed blank lines
- Added docstrings

2023-07-05 16:26 UTC, marksgraham approved these changes

2023-07-05 16:27 UTC, merged