Add dropout for conditioning cross-attention blocks.
Project-MONAI/GenerativeModels pull request #407
Opened 2023-06-27 13:09 UTC by virginiafdez

Added "dropout_cattn" parameter to add dropout on the conditioning cross-attention channels.
Does not apply dropout everywhere, just in the conditioning blocks.

2023-06-27 20:42 UTC, marksgraham requested changes
This looks good to me - but I think the test case should just be included with the others in the 'test_diffusion_model_unet` file!

2023-11-01 08:47 UTC, virginiafdez commented
@marksgraham  Done!

2023-11-01 14:16 UTC, marksgraham commented on tests/test_diffusion_model_unet.py
> +        net = DiffusionModelUNet(**input_param)
```suggestion
        _ = DiffusionModelUNet(**input_param)
```

2023-11-01 14:16 UTC, marksgraham commented on tests/test_diffusion_model_unet.py
> +            net = DiffusionModelUNet(**input_param)
```suggestion
            _ = DiffusionModelUNet(**input_param)
```

2023-11-01 14:18 UTC, merged